using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;
using UnityEngine.UI;

#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
#endif

namespace Kirara
{

#if UNITY_EDITOR
    [CustomEditor(typeof(UIBinder))]
    public class UIBinderInspector : Editor
    {
        public override void OnInspectorGUI()
        {
            var script = (UIBinder)target;
            if (GUILayout.Button("生成"))
            {
                script.EditorGenerateUI();
            }
            if (GUILayout.Button("绑定"))
            {
                script.EditorBindUI();
            }
            base.OnInspectorGUI();
        }
    }
#endif

    public class UIBinder : MonoBehaviour
    {

#if UNITY_EDITOR
        [SerializeField]
        private MonoBehaviour ui;

        [SerializeField]
        private string outputPath = "Scripts/Generated";

        [SerializeField]
        private List<Item> nameTypeComList;

        [Serializable]
        public class Item
        {
            public string fieldName;
            public string comTypeFullName;
            public Component com;

            public Item(string fieldName, string comTypeFullName, Component com)
            {
                this.fieldName = fieldName;
                this.comTypeFullName = comTypeFullName;
                this.com = com;
            }

            public void Deconstruct(out string fieldName, out string comTypeFullName, out Component com)
            {
                fieldName = this.fieldName;
                comTypeFullName = this.comTypeFullName;
                com = this.com;
            }
        }

        private HashSet<string> fieldNameSet;

        private const string declaration = "// This file is generated by UIBinder and should not be modified.\n";

        private const string begin = "{\n";
        private const string indent = "    ";
        private const string end = "}\n";
        private const string newline = "\n";

        private const string nsHeaderFormat = "namespace {0}\n";
        private const string classHeaderFormat = "public partial class {0}\n";

        private const string accessModifier = "public";

        private Dictionary<string, Type> identifierToType = new Dictionary<string, Type>()
        {
            {"btn", typeof(Button)},
            {"input", typeof(InputField)},
            {"text", typeof(Text)},
            {"img", typeof(Image)},
            {"tra", typeof(Transform)},
            {"dd", typeof(Dropdown)},
        };

        public void EditorGenerateUI()
        {
            if (ui == null)
            {
                Debug.LogWarning("ui == null");
                return;
            }
            nameTypeComList ??= new List<Item>();
            nameTypeComList.Clear();

            fieldNameSet ??= new HashSet<string>();
            fieldNameSet.Clear();

            Scan(transform);
            
            var type = ui.GetType();
            string classNamespace = type.Namespace;
            string className = type.Name;
            string classFullName = type.FullName;

            string text = GenerateText(classNamespace, className);

            WriteFile(text, classFullName);

            SaveScene();
        }

        private string GenerateText(string classNamespace, string className)
        {
            string nsHeader = string.Empty;
            string nsBegin = string.Empty;
            string nsIndent = string.Empty;
            string nsEnd = string.Empty;
            if (classNamespace != null)
            {
                nsHeader = string.Format(nsHeaderFormat, classNamespace);
                nsBegin = begin;
                nsIndent = indent;
                nsEnd = end;
            }

            string classHeader = string.Format(classHeaderFormat, className);
            string classBegin = begin;
            string classIndent = indent;
            string classEnd = end;

            var sb = new StringBuilder();
            sb.Append(declaration);
            sb.Append(nsHeader);
            sb.Append(nsBegin);
            sb.Append(nsIndent + classHeader);
            sb.Append(nsIndent + classBegin);

            foreach (var (fieldName, comTypeFullName, _) in nameTypeComList)
            {
                sb.Append(nsIndent + classIndent);
                sb.Append(accessModifier);
                sb.Append(' ');
                sb.Append(comTypeFullName);
                sb.Append(' ');
                sb.Append(fieldName);
                sb.Append(';');
                sb.Append(newline);
            }
            sb.Append(nsIndent + classEnd);
            sb.Append(nsEnd);
            return sb.ToString();
        }

        private void WriteFile(string text, string classFullname)
        {
            string outputDir = Path.Join(Application.dataPath, outputPath);
            string filename = classFullname + ".g.cs";
            string filePath = Path.Join(outputDir, filename);
            Directory.CreateDirectory(outputDir);
            File.WriteAllText(filePath, text, Encoding.UTF8);
        }

        private void Scan(Transform _transform)
        {
            if (_transform == null)
            {
                return;
            }
            Stack<Transform> stk = new();
            stk.Push(_transform);
            while (stk.Count > 0)
            {
                var cur = stk.Pop();

                string _name = cur.name
                    .Replace("(", "_")
                    .Replace(")", "_")
                    .Replace(" ", "");

                foreach (var (prefix, type) in identifierToType)
                {
                    if (_name.StartsWith(prefix) && cur.TryGetComponent(type, out var com))
                    {
                        if (fieldNameSet.Add(_name))
                        {
                            nameTypeComList.Add(new Item(_name, type.FullName, com));
                            break;
                        }
                        throw new Exception($"名称{cur.name}, {_name}有重复");
                    }
                }

                foreach (Transform child in cur)
                {
                    stk.Push(child);
                }
            }
        }

        public void EditorBindUI()
        {
            var type = ui.GetType();
            foreach (var (fieldName, _, com) in nameTypeComList)
            {
                var fieldInfo = type.GetField(fieldName);
                if (fieldInfo == null)
                {
                    Debug.LogWarning($"{type.FullName}不存在字段{fieldName}");
                    return;
                }
                fieldInfo.SetValue(ui, com);
            }

            SaveScene();
        }

        private void SaveScene()
        {
            EditorSceneManager.MarkSceneDirty(ui.gameObject.scene);

            // Prefab不是Preview Scene
            if (!EditorSceneManager.IsPreviewScene(ui.gameObject.scene))
            {
                // ArgumentException: EditorSceneManager.SetActive failed; you can not save a preview scene
                EditorSceneManager.SaveScene(ui.gameObject.scene);
            }
        }
#endif

    }
}